PUT http://localhost:8080/Training/deleteByDaillogKey
Content-Type: application/json

{
  "daillogId": 1,
  "deletename": "胡志远",
  "timeliness": 1
}

###
PUT http://localhost:8080/Training/updateByDaillogKeySelective
Content-Type: application/json

{
  "daillogId":1,
  "title": "打架2",
  "content": "杀人放火2",
  "planbegintime": "2021-05-18",
  "postponement": "asdfsfjsdn,dsajdklsjklda2",
  "planendtime": "2021-11-12",
  "begintime": "2021-11-18",
  "updatename": "焦凡超",
  "empId": 1
}

###
POST http://localhost:8080/Training/addDaillog
Content-Type: application/json

{
  "title": "打架",
  "content": "杀人放火",
  "daillogType": 1,
  "planbegintime": "2021-05-17",
  "postponement": "asdfsfjsdn,dsajdklsjklda",
  "planendtime": "2021-11-11",
  "begintime": "2021-11-17",
  "endtime": "2021-11-11",
  "addname": "JFC",
  "empId": 1
}

###
GET http://localhost:8080/Training/selectByDaillogKey/1
Accept: application/json

###
