PUT http://localhost:8080/Training/deleteByExamination
Content-Type: application/json

{
  "examinationId": 1,
  "deletename": "蔡锦康"
}

###

PUT http://localhost:8080/Training/updateByExaminationKey
Content-Type: application/json

{
  "examinationId": 1,
  "examinationname": "拉丁舞恰恰第一章考试",
  "updatename": "蔡锦康"
}

###
POST http://localhost:8080/Training/addExamination
Content-Type: application/json

{
  "examinationname": "计算机java第一章考试",
  "timeliness": 0,
  "addname": "蔡锦康",
  "classesId": 1,
  "teacherId": 1,
  "courseId": 3
}

###
GET http://localhost:8080/Training/selectAllExamination/1/3
Accept: application/json

###
