PUT http://localhost:8080/Training/deleteByInterview
Content-Type: application/json

{
  "interviewId": 1,
  "deletename": "蔡锦康"
}

###

PUT http://localhost:8080/Training/updateByInterviewKey
Content-Type: application/json

{
  "interviewId": 1,
  "interviewcontent": "作业未交",
  "updatename": "蔡锦康"
}

###
POST http://localhost:8080/Training/addInterview
Content-Type: application/json

{
  "interviewcontent": "今天学习还行",
  "timeliness": 0,
  "addname": "蔡锦康",
  "classesId": 1,
  "empId": 1,
  "studentId": 1
}

###
GET http://localhost:8080/Training/selectAllInterview/1/3
Accept: application/json

###